name: "Feature suggestion"
description: "You are missing a feature? Fill this form and I will take a look at it."
title: "Suggestion: "
labels: ["feature suggestion"]
assignees:
  - florian-berger

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this recipe suggestion! Please take the time and fill all fields.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I get in touch with you if I need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: wanted-feature
    attributes:
      label: Wanted feature?
      description: Please give the feature a short title
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Please describe the feature as detailled as possible.
    validations:
      required: false

  - type: textarea
    id: further-data
    attributes:
      label: Further information / Screenshots / Logs
      description: |
        If you have any further information, screenshots, or log files, you can enter them here. 
        To attach images, click this area to highlight it and then drag your files into it.
    validations:
      required: false